version: '3'

services:
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=ddcz
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db

